module.exports = [
  "1-1:Planet Ragol",
  "1-2:Torrential Woods",
  "1-3:Subterranean Den",
  "2-1:Infernal Cavern",
  "2-2:Deep Within",
  "2-3:The Mutation",
  "2-4:Waterway Shadow",
  "3-1:The Facility",
  "3-2:Machines Attack",
  "3-3:Central Control",
  "4-1:The Lost Ruins",
  "4-2:Buried Relics",
  "4-3:Hero & Daughter",
  "4-4:The Tomb Stirs",
  "4-5:Dark Inheritance",
  "Battle Training",
  "Magnitude of Metal",
  "Claiming a Stake",
  "The Value of Money",
  "Journalistic Pursuit",
  "The Fake in Yellow",
  "Native Research",
  "Forest of Sorrow",
  "Gran Squall",
  "Addicting Food",
  "The Lost Bride",
  "Waterfall Tears",
  "Black Paper",
  "Secret Delivery",
  "Soul of a Blacksmith",
  "Letter from Lionel",
  "The Grave's Butler",
  "Knowing One's Heart",
  "The Retired Hunter",
  "Dr. Osto's Research",
  "Unsealed Door",
  "Soul of Steel",
  "Doc's Secret Plan",
  "Seek my Master",
  "From the Depths",
  "Central Dome Fire Swirl",
  "Mop-up Operation #1",
  "Mop-up Operation #2",
  "Mop-up Operation #3",
  "Mop-up Operation #4",
  "Sweep-up Operation #1",
  "Sweep-up Operation #2",
  "Sweep-up Operation #3",
  "Sweep-up Operation #4",
  "Endless Nightmare #1",
  "Endless Nightmare #2",
  "Endless Nightmare #3",
  "Endless Nightmare #4",
  "Today's Rate",
  "Anomalous Ordeal #1",
  "Anomalous Ordeal #2",
  "Scarlet Realm #1",
  "Scarlet Realm #2",
  "Scarlet Realm #3",
  "Scarlet Realm #4",
  "Silent Afterimage #1",
  "Silent Afterimage #2",
  "MAXIMUM ATTACK 1 Ver2",
  "Maximum Attack 4th Stage -1A-",
  "Maximum Attack 4th Stage -1B-",
  "Maximum Attack 4th Stage -1C-",
  "Maximum Attack 4th Stage -1R-",
  "Maximum Attack E: Episode 1",
  "Random Attack Xrd Stage",
  "Random Attack Xrd REV 1",
  "The Missing Maracas",
  "Lost HEAT SWORD",
  "Lost ICE SPINNER",
  "Lost SOUL BLADE",
  "Lost HELL PALLASCH",
  "Fragments of a Memory",
  "Rappy's Holiday",
  "Rescue from Ragol",
  "Gallon's Treachery",
  "Forsaken Friends",
  "This Must Be The Place",
  "Road To Nowhere",
  "Towards the Future",
  "Tyrell's Ego",
  "Labyrinthine Trial",
  "Sugoroku",
  "Simulator 2.0",
  "Mine Offensive",
  "Endless: Episode 1",
  "Gallon's Plan",
  "Good Luck!",
  "AOL CUP -Sunset Base-",
  "Knight of Coral",
  "Christmas Fiasco",
  "Solstice Snafu",
  "Maximum Attack E: Forest",
  "Maximum Attack E: Cave",
  "Maximum Attack E: Mine",
  "Maximum Attack E: Ruins",
  "Hollow Battlefield: Forest",
  "Hollow Battlefield: Cave",
  "Hollow Battlefield: Mine",
  "Hollow Battlefield: Ruins",
  "5-1:Test/VR Temple 1",
  "5-2:Test/VR Temple 2",
  "5-3:Test/VR Temple 3",
  "5-4:Test/VR Temple 4",
  "5-5:Test/VR Temple 5",
  "6-1:Test/Spaceship 1",
  "6-2:Test/Spaceship 2",
  "6-3:Test/Spaceship 3",
  "6-4:Test/Spaceship 4",
  "6-5:Test/Spaceship 5",
  "7-1:From the Past",
  "7-2:Seeking Clues",
  "7-3:Silent Beach",
  "7-4:Central Control",
  "7-5:Isle of Mutants",
  "8-1:Below the Waves",
  "8-2:Desire's End",
  "8-3:Purple Lamplight",
  "Seat of the Heart",
  "Blue Star Memories",
  "Phantasmal World #1",
  "Phantasmal World #2",
  "Phantasmal World #3",
  "Phantasmal World #4",
  "Sweep-up Operation #5",
  "Sweep-up Operation #6",
  "Sweep-up Operation #7",
  "Sweep-up Operation #8",
  "Sweep-up Operation #9",
  "Penumbral Surge #1",
  "Penumbral Surge #2",
  "Penumbral Surge #3",
  "Penumbral Surge #4",
  "Penumbral Surge #5",
  "Penumbral Surge #6",
  "Anomalous Ordeal #3",
  "Anomalous Ordeal #4",
  "Anomalous Ordeal #5",
  "Gal Da Val's Darkness",
  "CAL's Clock Challenge",
  "MAXIMUM ATTACK 2 Ver2",
  "Maximum Attack 4th Stage -2A-",
  "Maximum Attack 4th Stage -2B-",
  "Maximum Attack 4th Stage -2C-",
  "Maximum Attack 4th Stage -2R-",
  "Maximum Attack E: VR",
  "Maximum Attack E: Gal Da Val",
  "Random Attack Xrd Stage",
  "Random Attack Xrd REV 2",
  "Lost SHOCK RIFLE",
  "Lost BIND ASSAULT",
  "Lost FILL CANNON",
  "Lost DEMON'S RAILGUN",
  "Lost CHARGE VULCAN",
  "Dream Messenger",
  "Revisiting Darkness",
  "Dolmolm Research",
  "The East Tower",
  "The West Tower",
  "Raid on Central Tower",
  "The Military Strikes Back",
  "Twilight Sanctuary",
  "Reach for the Dream",
  "Respective Tomorrow",
  "Endless: Episode 2",
  "Knight of Coral Advent",
  "A New Hope",
  "Festivity on the Beach",
  "Christmas Fiasco",
  "Pioneer Christmas",
  "Maximum Attack E: Temple",
  "Maximum Attack E: Spaceship",
  "Maximum Attack E: CCA",
  "Maximum Attack E: Seabed",
  "Maximum Attack E: Tower",
  "Hollow Reality: Temple",
  "Hollow Reality: Spaceship",
  "Hollow Phantasm: Jungle",
  "Hollow Phantasm: Seabed",
  "Hollow Phantasm: Tower",
  "9-1:Missing Research",
  "9-2:Data Retrieval",
  "9-3:Reality & Truth",
  "9-4:Pursuit",
  "9-5:The Chosen (1/2)",
  "9-6:The Chosen (2/2)",
  "9-7:Sacred Ground",
  "9-8:The Final Cycle",
  "Warrior's Pride",
  "The Restless Lion",
  "Pioneer Spirit",
  "荒野の果てに",
  "Black Paper's Dangerous Deal",
  "Black Paper's Dangerous Deal 2",
  "Point of Disaster",
  "The Robots' Reckoning",
  "War of Limits #1",
  "War of Limits #2",
  "War of Limits #3",
  "War of Limits #4",
  "War of Limits #5",
  "New Mop-Up Operation #1",
  "New Mop-Up Operation #2",
  "New Mop-Up Operation #3",
  "New Mop-Up Operation #4",
  "New Mop-Up Operation #5",
  "Sweep-up Operation #10",
  "Sweep-up Operation #11",
  "Sweep-up Operation #12",
  "Sweep-up Operation #13",
  "Sweep-up Operation #14",
  "MAXIMUM ATTACK 3 Ver2",
  "Maximum Attack 4th Stage -4A-",
  "Maximum Attack 4th Stage -4B-",
  "Maximum Attack 4th Stage -4C-",
  "Maximum Attack 4th Stage -4R-",
  "Maximum Attack E: Episode 4",
  "Random Attack Xrd REV 4",
  "Lost BERSERK BATON",
  "Lost SPIRIT STRIKER",
  "Beyond the Horizon",
  "LOGiN presents 勇場のマッチレース",
  "Christmas Fiasco",
  "Maximum Attack E: Crater",
  "Maximum Attack E: Desert",
  "Hollow Wasteland: Wilderness",
  "Hollow Wasteland: Desert"
]